"""
ZIP Exporter for StAnify Manifests

Creates comprehensive ZIP packages containing:
- manifest.json
- All panel images
- PDF export
- PPTX export
"""

import json
import zipfile
from pathlib import Path
from typing import Dict, Any

from ..manifest_contracts import RunManifest
from .pdf_exporter import export_manifest_to_pdf
from .pptx_exporter import export_manifest_to_pptx


def export_manifest_to_zip(manifest: RunManifest, out_path: str, temp_dir: str = None) -> str:
    """
    Export a complete manifest package as a ZIP file.
    
    Args:
        manifest: The manifest to export
        out_path: Path where the ZIP file should be saved
        temp_dir: Temporary directory for intermediate files (optional)
        
    Returns:
        Path to the created ZIP file
    """
    if temp_dir is None:
        temp_dir = Path(out_path).parent / "temp"
    
    temp_path = Path(temp_dir)
    temp_path.mkdir(exist_ok=True)
    
    run_id = manifest.task.run_id
    base_name = f"stanify_{run_id}"
    
    try:
        # Create temporary files
        manifest_file = temp_path / f"{base_name}.manifest.json"
        pdf_file = temp_path / f"{base_name}.pdf"
        pptx_file = temp_path / f"{base_name}.pptx"
        images_dir = temp_path / "images"
        images_dir.mkdir(exist_ok=True)
        
        # 1. Export manifest as JSON
        manifest_dict = manifest.dict()
        with open(manifest_file, 'w', encoding='utf-8') as f:
            json.dump(manifest_dict, f, indent=2, ensure_ascii=False)
        
        # 2. Export PDF
        export_manifest_to_pdf(manifest, str(pdf_file))
        
        # 3. Export PPTX
        export_manifest_to_pptx(manifest, str(pptx_file))
        
        # 4. Copy panel images
        image_files = []
        for panel in manifest.panels:
            if panel.image_uri and Path(panel.image_uri).exists():
                source_path = Path(panel.image_uri)
                dest_path = images_dir / f"panel_{panel.chunk_id}{source_path.suffix}"
                
                # Copy image file
                with open(source_path, 'rb') as src, open(dest_path, 'wb') as dst:
                    dst.write(src.read())
                
                image_files.append(dest_path)
        
        # 5. Create ZIP package
        with zipfile.ZipFile(out_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            # Add manifest
            zipf.write(manifest_file, f"{base_name}.manifest.json")
            
            # Add exports
            zipf.write(pdf_file, f"{base_name}.pdf")
            zipf.write(pptx_file, f"{base_name}.pptx")
            
            # Add images
            for img_file in image_files:
                zipf.write(img_file, f"images/{img_file.name}")
            
            # Add README
            readme_content = f"""# StAnify Educational Content Package

## Contents
- {base_name}.manifest.json - Complete content manifest with metadata
- {base_name}.pdf - Educational content as PDF with cover and assessment pages
- {base_name}.pptx - Educational content as PowerPoint presentation
- images/ - All panel images used in the content

## Manifest Details
- Run ID: {run_id}
- Year/Subject: {manifest.task.year} {manifest.task.subject}
- Topic: {manifest.refined_prompt.topic_title} ({manifest.refined_prompt.topic_id})
- Panels: {len(manifest.panels)}
- Generated by: StAnify AI Educational Platform

## Quality Assessment
"""
            if manifest.overall_critique:
                critique = manifest.overall_critique
                readme_content += f"- Overall Verdict: {critique.verdict}\n"
                if hasattr(critique, 'scores') and critique.scores:
                    scores = critique.scores
                    readme_content += f"- Quality Scores: Clarity: {getattr(scores, 'clarity', 'N/A')}, "
                    readme_content += f"Engagement: {getattr(scores, 'engagement', 'N/A')}, "
                    readme_content += f"Accuracy: {getattr(scores, 'accuracy', 'N/A')}\n"
            else:
                readme_content += "- Quality assessment not available\n"
            
            readme_content += f"""
## Usage
1. View the PDF for a complete lesson with objectives and assessment
2. Use the PPTX for interactive classroom presentation
3. Reference the manifest.json for technical details and metadata
4. Access individual images in the images/ folder for custom use

Generated on: {manifest.task.run_id[:8]}...
Platform: StAnify - AI-powered educational content generator
"""
            
            zipf.writestr("README.md", readme_content)
        
        return out_path
        
    finally:
        # Cleanup temporary files
        try:
            import shutil
            if temp_path.exists():
                shutil.rmtree(temp_path)
        except Exception:
            pass  # Ignore cleanup errors


def create_export_package(manifest: RunManifest, base_output_dir: str) -> Dict[str, str]:
    """
    Create all export formats for a manifest.
    
    Args:
        manifest: The manifest to export
        base_output_dir: Base directory for outputs
        
    Returns:
        Dictionary with paths to all created files
    """
    output_dir = Path(base_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    run_id = manifest.task.run_id
    base_name = f"stanify_{run_id}"
    
    exports = {}
    
    try:
        # Individual exports
        exports['manifest'] = str(output_dir / f"{base_name}.manifest.json")
        exports['pdf'] = str(output_dir / f"{base_name}.pdf")
        exports['pptx'] = str(output_dir / f"{base_name}.pptx")
        exports['zip'] = str(output_dir / f"{base_name}.zip")
        
        # Create manifest JSON
        with open(exports['manifest'], 'w', encoding='utf-8') as f:
            json.dump(manifest.dict(), f, indent=2, ensure_ascii=False)
        
        # Create PDF and PPTX
        export_manifest_to_pdf(manifest, exports['pdf'])
        export_manifest_to_pptx(manifest, exports['pptx'])
        
        # Create comprehensive ZIP
        export_manifest_to_zip(manifest, exports['zip'], str(output_dir / "temp"))
        
        return exports
        
    except Exception as e:
        # Return partial results if some exports failed
        return {k: v for k, v in exports.items() if Path(v).exists()}
